# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'


default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: smyth
  port: 5432
  password: 
  username: smyth

test:
  <<: *default
  database: ben_test_db
  port: 5433
  password: harvey
  username: postgres

production:
  <<: *default
  database: dcj40nr4jm177d
  port: 5432
  password: EXCjqsOlidVzSb4RvWrd_F_1al
  username: yuersocslviddi